# Generated by Django 3.1.4 on 2021-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
